policeuk:
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH') }}"
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: "{{ env_var('S3_REGION') }}"
        s3_endpoint: "{{ env_var('S3_ENDPOINT') }}"
        s3_url_style: 'path'
        s3_use_ssl: false
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"
      threads: 2

  target: dev